config/routes.rb
Procarrierwave::Application.routes.draw do
  resources :sites

  get "site/index"

   root :to => "site#index"

  match ':controller(/:action(/:id(.:format)))'

end

app/models/site.rb
class Site < ActiveRecord::Base

	require 'carrierwave/orm/activerecord'

	attr_accessible :attachment
	validates_presence_of :attachment #use if the attribute is required
	mount_uploader :attachment, AttachmentUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper :all
end

app/controllers/sites_controller.rb
# encoding: utf-8


class SitesController < ApplicationController

  # GET /sites
  # GET /sites.xml
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = Site.new(params[:site])

    

    respond_to do |format|
      if @site.save
        format.html { redirect_to(@site, :notice => 'Site was successfully created.') }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Site was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.remove_attachment!
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Procarrierwave</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site, :html => { :multipart => true }) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= image_tag(@site.attachment_url) if @site.attachment? %>
  <%= link_to_if(@site.attachment?, "Descargar fichero", @site.attachment_url) %>
  <%= f.label :attachment %>
  <%= f.file_field :attachment %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editar fichero</h1>

<%= render 'form' %>

<%= link_to 'Ver', @site %> |
<%= link_to 'Volver', sites_path %>

app/views/sites/index.html.erb
<h1>Listado de ficheros</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= link_to 'Ver', site %></td>
    <td><%= link_to 'Editar', edit_site_path(site) %></td>
    <td><%= link_to 'Borrar', site, :confirm => 'estas seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo fichero', new_site_path %>

app/views/sites/new.html.erb
<h1>Nuevo fichero</h1>

<%= render 'form' %>

<%= link_to 'Volver', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@site.attachment_url) if @site.attachment? %>
<%= link_to_if(@site.attachment?, "Descargar fichero", @site.attachment_url) %>

<%= link_to 'Editar', edit_site_path(@site) %> |
<%= link_to 'Volver', sites_path %>